* Въведение в системите за управление на бази от данни
** 1. Избройте някои от предимствата на използването на СУБД пред системите за работа с файлове. (7) – дублирането на данните е премахнато, неконсистентността е ограничена, данните са интегрирани, данните са споделени, премахната е зависимостта, сложни обекти могат да бъдат лесно преставяни, могат да бъдат наложени стандарти и ограничения
* Архитектура на СУБД
** 2. Какво може да се постигне, ако е възможна промяна на концептуалната схема без това да наложи промяна на външната? (2)-логическа независимост
** 3. Какви са отговорностите на администратора на СУБД? (6) – архивиране и възтановяване, увеличаване на хардуерните и софтуерни ресурси при необходимост, контрол на достъпа до БД
* Обща характеристика на релационните СУБД
** 4. Кои са компонентите (аспектите) на релационния модел? (3) – структурна част, правила за цялостност на данните, манипулативна част
* Релации
** 5. Избройте свойствата на релациите. (4) – няма дублиращи се записи, атрибутите и записите са неподредени и стойностите са атомарни
** 6. Избройте 3 вида релации. (3) – именувани , базови и дериватни
* Кандидат-ключове
** 7. Напишете дефиниция (формална) на кандидат-ключ. (4) – минимално подмножество от атрибути на дадена релация, което уникално идентифицира дадена н-орка.
** 8. Кой ключ-кандидат е прост? (2) – който има 1 атрибут
* Външни ключове
** 9. Може ли външен ключ да е съставен и ако да, кога се случва това? (2) – да, ако първичния ключ на таблицата която референцираме е съставен, тогава и външния е съставен.
** 10. Опишете какви са подходите при опит да се промени един първичен ключ, който е целева референция на външен ключ. (2) – Cascade ,restricted
* Нулеви стойности
** 11. Какво е нулева стойност? (2) – липса на данни
** 12. Може ли външен ключ да приема нулева стойност? (2) - може
* Релационна алгебра
** 13. Какво е релационна затвореност? (2) – резултатът на една релационна операция винаги е нова релация
** 14. Напишете дефиниция на релационния оператор INTERSECTION (сечение). (4) – създава релация, която съдържа записи ,които се съдържат само във двете релации едновременно.
* Функционални зависимости
** 15. Какво представлява затвореност на едно множество от функционални зависимости? (2) – множество на всички ФЗ, които следват от едно дадено множество S  от ФЗ
** 16. Напишете аксиомите на Армстронг. (3)
* Теория на нормализацията
** 17. Напишете теоремата на Хийт. (4)
** 18. Напишете дефиниция на втора нормална форма. (4) – всички неключови атрубути зависят от целия първичен ключ
* Възстановяване
** 19. Какво е транзакция? (3) – логическа единица за опериране върху БД
** 20. Кои транзакции са кандидати за undo и какво се случва при рестарт на системата с тях? (4) – състоянието им не е известно в момента на пропадане, при рестарт трябва да бъдат отменени
* Конкурентност
** 21. Какво е конкурентност? (3) – когато 2 транзакции искат да достъпят едни и същи данни едновременно
** 22. Избройте възможни проблеми, възникващи при конкурентността. (4) – загуба на промяната, несвършена зависимост, неконсистентен анализ, четене на редове фантоми
* Сигурност
** 23. Какво разбираме под „сигурност” на данните? (3) – защита на данните срещу неоторизирано търсене промяна и изтриване
