* Въведение в системите за управление на бази от данни
** 1. Какви данни съдържа една база от данни? (2) – оперативни, данни които описват тези данни(речници)
** 2. Какви са режимите на работа на СУБД? (2) - 
** 3. Могат ли изходните данни да станат част от БД (т.е. оперативни)? (2) - не

* Архитектура на СУБД
** 4. Избройте модели СУБД. (5) – релационен модел, файлови системи, електронни таблици, йерархичен модел, мрежови модел....
** 5. Какво определят кореспонденциите между външното и концептуално ниво (external/conceptual mapping)? (3) – начина на представяне на данните от потребителска гледна точка
** 6. Какво означава СУБД да е релационна? (4) – да е колекция от свързани помежду си релации и да отговаря на правилата на Кодд

* Кандидат-ключове
** 7. Кои ключове са алтернативни? (2) – кандидат ключове които не са избрани за първични

* Външни ключове
** 8. Какво е референциално ограничение? (2) – ограничението, че стойностите на един ВК трябва да съответстват на стойностите на съответния ПК
** 9. Какво е референциален път? (4) – последователността от референциални ограничения от Rn до R1 представя референциален път от Rn до R1

* Релационна алгебра
** 10. Напишете дефиниция на релационния оператор JOIN (сливане). (5) –слива две релации със общи атрибути и общи стойности
** 11. Напишете дефиниция на релационния оператор SUMMARIZE. (5) – извършва вертикални изчисления
** 12. Напишете дефиниция на релационния оператор PRODUCT (произведение). (5) – връща нова релация, която се състои от всички възможни конкатенирани двойки от записи от двете релации
** 13. Напишете дефиниция на релационния оператор DIFFERENCE (разлика). (5) – създава релация, която съдържа записи от първата релация, които не се съдържат във втората

* Теория на нормализацията
** 14. Напишете дефиниция на четвърта нормална форма. (4) - 
** 15. Напишете дефиниция на Domain/Key нормална форма. (4) - 
** 16. Допустим ли е процес на денормализация и ако да, посочете поне една причина. (2) – да, когато таблицата се нормализира прекалено много

* Възстановяване
** 17. Как системата различава undo и redo транзакциите? (6) 
